export interface RespiratoryMedicationPreset {
  name: string;
  genericName: string;
  category: "Inhaler / DPI" | "Nebuliser" | "Oral Tablet / Capsule" | "Injectable / Biologic" | "Nasal Spray";
  defaultRoute: "inhaler" | "nebulisation" | "tablet" | "capsule" | "inj" | "nasal_spray";
  commonDoses: string[];
  commonFrequencies: string[];
}

export const RESPIRATORY_MEDICATION_PRESETS: RespiratoryMedicationPreset[] = [
  // ── Inhalers & Rotacaps (DPI / MDI) ──────────────────────────────────────
  {
    name: "Foracort Inhaler / Rotacaps",
    genericName: "Formoterol + Budesonide",
    category: "Inhaler / DPI",
    defaultRoute: "inhaler",
    commonDoses: ["200 mcg", "400 mcg", "100 mcg", "100/6 mcg", "200/6 mcg", "400/6 mcg"],
    commonFrequencies: ["1 puff BD", "2 puffs BD", "1 rotacap BD", "1 puff OD"],
  },
  {
    name: "Budecort Inhaler / Rotacaps",
    genericName: "Budesonide",
    category: "Inhaler / DPI",
    defaultRoute: "inhaler",
    commonDoses: ["100 mcg", "200 mcg", "400 mcg"],
    commonFrequencies: ["1 puff BD", "2 puffs BD", "1 rotacap BD"],
  },
  {
    name: "Seroflo Inhaler / Rotacaps",
    genericName: "Salmeterol + Fluticasone Propionate",
    category: "Inhaler / DPI",
    defaultRoute: "inhaler",
    commonDoses: ["125 mcg", "250 mcg", "500 mcg", "50/100 mcg", "50/250 mcg"],
    commonFrequencies: ["1 puff BD", "2 puffs BD", "1 rotacap BD"],
  },
  {
    name: "Tiova Inhaler / Rotacaps",
    genericName: "Tiotropium Bromide",
    category: "Inhaler / DPI",
    defaultRoute: "inhaler",
    commonDoses: ["9 mcg", "18 mcg"],
    commonFrequencies: ["1 rotacap OD (Morning)", "2 puffs OD", "1 puff OD"],
  },
  {
    name: "Duolin Inhaler / Respules",
    genericName: "Levosalbutamol + Ipratropium Bromide",
    category: "Inhaler / DPI",
    defaultRoute: "inhaler",
    commonDoses: ["50/20 mcg", "1.25mg / 500mcg"],
    commonFrequencies: ["1 puff TDS", "2 puffs BD", "1 respule TDS SOS", "1 respule BD"],
  },
  {
    name: "Asthalin Inhaler",
    genericName: "Salbutamol",
    category: "Inhaler / DPI",
    defaultRoute: "inhaler",
    commonDoses: ["100 mcg"],
    commonFrequencies: ["2 puffs SOS for breathlessness", "1 puff TDS", "2 puffs BD"],
  },
  {
    name: "Aerocort Inhaler / Rotacaps",
    genericName: "Levosalbutamol + Beclomethasone",
    category: "Inhaler / DPI",
    defaultRoute: "inhaler",
    commonDoses: ["50/50 mcg", "100/100 mcg"],
    commonFrequencies: ["1 puff BD", "2 puffs BD", "1 rotacap BD"],
  },
  {
    name: "Maxiflo Inhaler / Rotacaps",
    genericName: "Formoterol + Fluticasone",
    category: "Inhaler / DPI",
    defaultRoute: "inhaler",
    commonDoses: ["125 mcg", "250 mcg"],
    commonFrequencies: ["1 puff BD", "2 puffs BD"],
  },
  {
    name: "Symbicort Turbuhaler",
    genericName: "Budesonide + Formoterol",
    category: "Inhaler / DPI",
    defaultRoute: "inhaler",
    commonDoses: ["160/4.5 mcg", "320/9 mcg", "80/4.5 mcg"],
    commonFrequencies: ["1-2 puffs BD SMART regimen", "1 puff BD"],
  },
  {
    name: "Seebri Breezhaler",
    genericName: "Glycopyrronium",
    category: "Inhaler / DPI",
    defaultRoute: "inhaler",
    commonDoses: ["50 mcg"],
    commonFrequencies: ["1 capsule OD (Morning)"],
  },
  {
    name: "Ultibro Breezhaler",
    genericName: "Indacaterol + Glycopyrronium",
    category: "Inhaler / DPI",
    defaultRoute: "inhaler",
    commonDoses: ["110/50 mcg"],
    commonFrequencies: ["1 capsule OD (Morning)"],
  },
  {
    name: "Trelegy Ellipta",
    genericName: "Fluticasone Furoate + Umeclidinium + Vilanterol",
    category: "Inhaler / DPI",
    defaultRoute: "inhaler",
    commonDoses: ["100/62.5/25 mcg", "200/62.5/25 mcg"],
    commonFrequencies: ["1 inhalation OD"],
  },

  // ── Nebuliser Formulations ───────────────────────────────────────────────
  {
    name: "Budecort Respules",
    genericName: "Budesonide Nebulising Suspension",
    category: "Nebuliser",
    defaultRoute: "nebulisation",
    commonDoses: ["0.5 mg", "1.0 mg"],
    commonFrequencies: ["1 respule BD", "1 respule OD", "1 respule TDS"],
  },
  {
    name: "Duolin Respules",
    genericName: "Levosalbutamol + Ipratropium Nebuliser Solution",
    category: "Nebuliser",
    defaultRoute: "nebulisation",
    commonDoses: ["2.5 ml"],
    commonFrequencies: ["1 respule BD", "1 respule TDS", "1 respule QID SOS"],
  },
  {
    name: "Mucomix Respules",
    genericName: "Acetylcysteine",
    category: "Nebuliser",
    defaultRoute: "nebulisation",
    commonDoses: ["200 mg / 1 ml", "2 ml"],
    commonFrequencies: ["1 respule BD with normal saline"],
  },
  {
    name: "Hypertonic Saline 3% / 7%",
    genericName: "Hypertonic Saline Nebulisation Solution",
    category: "Nebuliser",
    defaultRoute: "nebulisation",
    commonDoses: ["4 ml 3%", "4 ml 7%"],
    commonFrequencies: ["1 ampoule BD before chest physiotherapy"],
  },

  // ── Oral Medications (ILD / Antifibrotics / Bronchodilators / Steroids) ──
  {
    name: "Pirfenex / Pirfenidone",
    genericName: "Pirfenidone",
    category: "Oral Tablet / Capsule",
    defaultRoute: "tablet",
    commonDoses: ["200 mg", "400 mg", "600 mg", "801 mg"],
    commonFrequencies: ["200mg TDS post meals", "400mg TDS post meals", "600mg TDS", "801mg TDS"],
  },
  {
    name: "Nintedanib / Nintena / Cyndat",
    genericName: "Nintedanib",
    category: "Oral Tablet / Capsule",
    defaultRoute: "capsule",
    commonDoses: ["100 mg", "150 mg"],
    commonFrequencies: ["100 mg BD with food", "150 mg BD with food"],
  },
  {
    name: "Montair-LC",
    genericName: "Montelukast 10mg + Levocetirizine 5mg",
    category: "Oral Tablet / Capsule",
    defaultRoute: "tablet",
    commonDoses: ["10/5 mg"],
    commonFrequencies: ["1 tab OD at bedtime"],
  },
  {
    name: "N-Acetylcysteine (NAC) Effervescent",
    genericName: "Acetylcysteine",
    category: "Oral Tablet / Capsule",
    defaultRoute: "tablet",
    commonDoses: ["600 mg", "1200 mg"],
    commonFrequencies: ["1 effervescent tab OD in 100ml water", "1 tab BD"],
  },
  {
    name: "Deriphyllin Retard",
    genericName: "Theophylline + Etofylline",
    category: "Oral Tablet / Capsule",
    defaultRoute: "tablet",
    commonDoses: ["150 mg", "300 mg"],
    commonFrequencies: ["1 tab BD post meals", "1 tab OD"],
  },
  {
    name: "Doxolin / Doxofylline",
    genericName: "Doxofylline",
    category: "Oral Tablet / Capsule",
    defaultRoute: "tablet",
    commonDoses: ["400 mg", "650 mg"],
    commonFrequencies: ["1 tab BD post meals", "1 tab OD"],
  },
  {
    name: "Wysolone / Prednisolone",
    genericName: "Prednisolone",
    category: "Oral Tablet / Capsule",
    defaultRoute: "tablet",
    commonDoses: ["5 mg", "10 mg", "20 mg", "40 mg"],
    commonFrequencies: ["1 tab OD morning after breakfast (tapering)", "10mg OD", "20mg OD"],
  },
  {
    name: "Defcort / Deflazacort",
    genericName: "Deflazacort",
    category: "Oral Tablet / Capsule",
    defaultRoute: "tablet",
    commonDoses: ["6 mg", "12 mg", "18 mg", "24 mg"],
    commonFrequencies: ["1 tab OD morning post meals", "6mg OD", "12mg OD"],
  },
  {
    name: "Azithromycin (Maintenance / Anti-inflammatory)",
    genericName: "Azithromycin",
    category: "Oral Tablet / Capsule",
    defaultRoute: "tablet",
    commonDoses: ["250 mg", "500 mg"],
    commonFrequencies: ["250 mg Mon-Wed-Fri (3x/week)", "500 mg 3 days/week", "500 mg OD x 5 days"],
  },
  {
    name: "Mycophenolate Mofetil (MMF / Cellcept)",
    genericName: "Mycophenolate Mofetil",
    category: "Oral Tablet / Capsule",
    defaultRoute: "tablet",
    commonDoses: ["500 mg", "1000 mg"],
    commonFrequencies: ["500 mg BD", "1000 mg BD", "1500 mg BD"],
  },
  {
    name: "Azathioprine (Imuran)",
    genericName: "Azathioprine",
    category: "Oral Tablet / Capsule",
    defaultRoute: "tablet",
    commonDoses: ["50 mg"],
    commonFrequencies: ["50 mg OD", "50 mg BD post food"],
  },

  // ── Nasal Sprays (Upper Airway Co-morbidities / Allergic Rhinitis) ────────
  {
    name: "Fluticasone Furoate Nasal Spray (Flomist / Avamys)",
    genericName: "Fluticasone Furoate",
    category: "Nasal Spray",
    defaultRoute: "nasal_spray",
    commonDoses: ["27.5 mcg/spray"],
    commonFrequencies: ["2 sprays per nostril OD morning", "1 spray per nostril BD"],
  },
  {
    name: "Azelastine + Fluticasone (Azep-FT / Dymista)",
    genericName: "Azelastine Hydrochloride + Fluticasone Propionate",
    category: "Nasal Spray",
    defaultRoute: "nasal_spray",
    commonDoses: ["140/50 mcg/spray"],
    commonFrequencies: ["1 spray per nostril BD"],
  },
];
